# Generated by Django 5.0.6 on 2024-07-07 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('orgId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('lastName', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(10)])),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(10)])),
                ('organisations', models.ManyToManyField(blank=True, related_name='users', to='authentication.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
